// lib/eventData.ts — Single source of truth for all 100 AllSport events.

export type InputMode =
  | 'strength'
  | 'reps'
  | 'time'
  | 'hold'
  | 'distance'
  | 'flexibility'
  | 'sport'
  | 'weight+time'
  | 'distance+time'
  | 'sprint'
  | 'dynamic'

export type DifficultyTier = {
  level: number
  name: string
}

export type DisadvantageOptions = {
  small: [string, string, string]
  large: [string, string, string]
}

export type EventData = {
  slug: string
  name: string
  domain: string
  domainNumber: number
  inputMode: InputMode
  hasDifficultyTiers: boolean
  difficultyTiers?: DifficultyTier[]
  howToPerform: string
  rules: string
  disadvantage: DisadvantageOptions
  videoPlaceholder: boolean
  emoji: string
}

export type BonusTarget = {
  tier: 1 | 2 | 3 | 4
  label: string
  detail: string
  points: 15
  inputMode: string
}

const PLACEHOLDER_DISADVANTAGE: DisadvantageOptions = {
  small: ['Option A', 'Option B', 'Option C'],
  large: ['Option A', 'Option B', 'Option C'],
}

const PLACEHOLDER_CONTENT = 'Content coming soon.'

export const EVENTS: EventData[] = [
  // ─── Domain 1: Maximal Strength ─────────────────────────────────────────────
  {
    slug: '1-arm-press',
    name: '1 Arm Press',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💪',
  },
  {
    slug: 'deadlift',
    name: 'Deadlift',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: 'Stand with feet hip-width apart, barbell over mid-foot. Hinge at the hips, grip the bar just outside your legs. Brace your core, take a breath, and drive through the floor to stand tall. Lock out at the top with hips and knees fully extended. Lower under control.',
    rules: 'Starting position must be a dead stop on the floor. Full lockout required at the top — hips and knees fully extended, standing tall. No hitching (using thighs as a ramp). Standard or sumo stance allowed. Any grip allowed. Belt and straps permitted.',
    disadvantage: {
      small: ['Pause at knee on the way up', 'Deficit pull — stand on 10cm platform', 'One hand only'],
      large: ['Pause at floor + knee + lockout', 'Band resistance added', 'One leg only'],
    },
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'overhead-press',
    name: 'Overhead Press',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'pause-dips',
    name: 'Pause Dips',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💪',
  },
  {
    slug: 'pause-chin-up',
    name: 'Pause Chin Up',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💪',
  },
  {
    slug: 'pause-squat',
    name: 'Pause Squat',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'zercher-deadlift',
    name: 'Zercher Deadlift',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'hamstring-curl',
    name: 'Hamstring Curl',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦵',
  },
  {
    slug: 'pause-bench-press',
    name: 'Pause Bench Press',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'turkish-get-up',
    name: 'Turkish Get-Up',
    domain: 'Maximal Strength',
    domainNumber: 1,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },

  // ─── Domain 2: Relative Strength ─────────────────────────────────────────────
  {
    slug: '1-leg-squat',
    name: '1 Leg Squat',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Assisted Lunge' },
      { level: 2, name: 'Lunge' },
      { level: 3, name: 'Bulgarian Split Squat' },
      { level: 4, name: 'Shrimp Squat' },
      { level: 5, name: 'Pistol Squat' },
      { level: 6, name: 'Dragon Squat' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦵',
  },
  {
    slug: 'flag',
    name: 'Flag',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'dynamic',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Knee Side Plank' },
      { level: 2, name: 'Side Plank' },
      { level: 3, name: 'One Leg Side Plank' },
      { level: 4, name: 'Jumping Side Plank' },
      { level: 5, name: 'Top Flag' },
      { level: 6, name: 'Half Flag' },
      { level: 7, name: 'Human Flag' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🚩',
  },
  {
    slug: 'windshield-wipers',
    name: 'Windshield Wipers',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Lying Tuck Twists' },
      { level: 2, name: 'Lying L Twist' },
      { level: 3, name: 'Hanging Circles' },
      { level: 4, name: 'Windshield Wipers' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🌀',
  },
  {
    slug: 'toe-lift',
    name: 'Toe Lift',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦶',
  },
  {
    slug: 'planche',
    name: 'Planche',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'dynamic',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Wall Lean' },
      { level: 2, name: 'Pseudo Planche Lean' },
      { level: 3, name: 'Elevated Pseudo Planche' },
      { level: 4, name: 'Tuck Planche' },
      { level: 5, name: 'Advanced Tuck' },
      { level: 6, name: 'Straddle Planche' },
      { level: 7, name: 'Full Planche' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'back-lever',
    name: 'Back Lever',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'dynamic',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Inverted Hang' },
      { level: 2, name: 'Skin the Cat Hold' },
      { level: 3, name: 'Tuck' },
      { level: 4, name: 'Advanced Tuck' },
      { level: 5, name: 'One Leg' },
      { level: 6, name: 'Straddle' },
      { level: 7, name: 'Full Back Lever' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'iron-cross',
    name: 'Iron Cross',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'dynamic',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Inverted Weight Hold' },
      { level: 2, name: 'Heavy Band Assisted' },
      { level: 3, name: 'Light Band Assisted' },
      { level: 4, name: 'Ring Support Hold' },
      { level: 5, name: 'Partial Iron Cross' },
      { level: 6, name: 'Full Iron Cross' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '✚',
  },
  {
    slug: 'front-lever',
    name: 'Front Lever',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'dynamic',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Arch Hang' },
      { level: 2, name: 'Tuck' },
      { level: 3, name: 'Advanced Tuck' },
      { level: 4, name: 'One Leg' },
      { level: 5, name: 'Straddle' },
      { level: 6, name: 'Full Front Lever' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'chin-hang',
    name: 'Chin Hang',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Two-Hand Two-Foot Assisted' },
      { level: 2, name: 'Two-Hand One-Foot Assisted' },
      { level: 3, name: 'Two-Hand Chin Hang' },
      { level: 4, name: 'One-Hand Chin Hang' },
      { level: 5, name: 'Chin Hang (Band Assisted)' },
      { level: 6, name: 'Hands-Free Chin Hang' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🧗',
  },
  {
    slug: 'rope-climb',
    name: 'Rope Climb',
    domain: 'Relative Strength',
    domainNumber: 2,
    inputMode: 'time',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Foot Assisted Rope Climb' },
      { level: 2, name: 'Rope Climb' },
      { level: 3, name: 'L Sit Rope Climb' },
      { level: 4, name: 'Pegboard (feet)' },
      { level: 5, name: 'Pegboard (no feet)' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🪢',
  },

  // ─── Domain 3: Muscular Endurance ─────────────────────────────────────────────
  {
    slug: 'chin-up-contest',
    name: 'Chin Up Contest',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: 'Start from a dead hang with palms facing you (supinated grip), hands shoulder-width apart. Pull your chin above the bar on every rep. Return to full dead hang between reps. Count total reps completed without stopping.',
    rules: 'Palms facing toward you (supinated grip). Full dead hang at the bottom of each rep — elbows fully extended. Chin must clear the bar on every rep. Kipping not allowed. No momentum from legs. Score is total reps completed in one continuous set.',
    disadvantage: {
      small: ['Weighted vest 5kg', 'Pause at top each rep (2 seconds)', 'Narrow grip (hands 10cm apart)'],
      large: ['Weighted vest 10kg', 'One arm assist only', 'Towel grip both hands'],
    },
    videoPlaceholder: true,
    emoji: '💪',
  },
  {
    slug: 'push-up-contest',
    name: 'Push Up Contest',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💪',
  },
  {
    slug: 'reverse-hyper',
    name: 'Reverse Hyper',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Knees' },
      { level: 2, name: 'Hips' },
      { level: 3, name: 'Belly Button' },
      { level: 4, name: 'Chest' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🔄',
  },
  {
    slug: 'l-sit-hold',
    name: 'L-Sit Hold',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Foot Supported' },
      { level: 2, name: 'One Foot Down' },
      { level: 3, name: 'Tucked L Sit' },
      { level: 4, name: 'One Leg Extended' },
      { level: 5, name: 'Full L Sit' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🪑',
  },
  {
    slug: 'tibialis-curl',
    name: 'Tibialis Curl',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦵',
  },
  {
    slug: 'headstand',
    name: 'Headstand',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Tripod (feet on ground)' },
      { level: 2, name: 'Tripod Headstand' },
      { level: 3, name: 'Forearm Headstand' },
      { level: 4, name: 'Wall Headstand' },
      { level: 5, name: 'Freestanding Headstand' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🙃',
  },
  {
    slug: 'finger-push-up',
    name: 'Finger Push Up',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Assisted Fist Pushup' },
      { level: 2, name: 'Fist Pushup' },
      { level: 3, name: 'Finger Pushup' },
      { level: 4, name: 'Four Finger' },
      { level: 5, name: 'Three Finger' },
      { level: 6, name: 'Two Finger' },
      { level: 7, name: 'Thumb Only' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '👆',
  },
  {
    slug: 'calf-raise',
    name: 'Calf Raise',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦵',
  },
  {
    slug: 'leg-extension',
    name: 'Leg Extension',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦵',
  },
  {
    slug: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    domain: 'Muscular Endurance',
    domainNumber: 3,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Kneeling (Partial)' },
      { level: 2, name: 'Kneeling (Full)' },
      { level: 3, name: 'Kneeling (Elevated)' },
      { level: 4, name: 'Standing (Band Assisted)' },
      { level: 5, name: 'Standing' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚙️',
  },

  // ─── Domain 4: Flexibility & Mobility ────────────────────────────────────────
  {
    slug: 'rear-hand-clasp',
    name: 'Rear Hand Clasp',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🙏',
  },
  {
    slug: 'bridge',
    name: 'Bridge',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Wall Backbend' },
      { level: 2, name: 'Deep Wall Backbend' },
      { level: 3, name: 'Assisted Floor Bridge' },
      { level: 4, name: 'Floor Bridge' },
      { level: 5, name: 'Straight Arm Bridge' },
      { level: 6, name: 'Wheel Pose' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🌉',
  },
  {
    slug: 'forward-fold',
    name: 'Forward Fold',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Forward Fold' },
      { level: 2, name: 'To Shins' },
      { level: 3, name: 'Touch Floor' },
      { level: 4, name: 'Head to Knees' },
      { level: 5, name: 'Head to Legs' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🧘',
  },
  {
    slug: 'needle-pose',
    name: 'Needle Pose',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: '90/90 Pose' },
      { level: 2, name: '90/90 Lift' },
      { level: 3, name: 'Standing Scale (Knee)' },
      { level: 4, name: 'Standing Scale (Hip)' },
      { level: 5, name: 'Standing Scale (High)' },
      { level: 6, name: 'Needle Pose' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🪡',
  },
  {
    slug: 'front-split',
    name: 'Front Split',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'middle-split',
    name: 'Middle Split',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'standing-split',
    name: 'Standing Split',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Ankle' },
      { level: 2, name: 'Knee' },
      { level: 3, name: 'Hip' },
      { level: 4, name: 'Ribs' },
      { level: 5, name: 'Shoulder' },
      { level: 6, name: 'Head' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'foot-behind-head',
    name: 'Foot Behind Head',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Assisted Pigeon' },
      { level: 2, name: '90/90 Stretch' },
      { level: 3, name: 'Floor Pigeon' },
      { level: 4, name: 'Raised Pigeon' },
      { level: 5, name: 'Foot to Head' },
      { level: 6, name: 'Foot Behind Head' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦶',
  },
  {
    slug: 'shoulder-dislocate',
    name: 'Shoulder Dislocate',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Shoulder Width +30cm' },
      { level: 2, name: 'Shoulder Width +20cm' },
      { level: 3, name: 'Shoulder Width +10cm' },
      { level: 4, name: 'Shoulder Width' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🌀',
  },
  {
    slug: 'side-bend',
    name: 'Side Bend',
    domain: 'Flexibility & Mobility',
    domainNumber: 4,
    inputMode: 'flexibility',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🧘',
  },

  // ─── Domain 5: Power ─────────────────────────────────────────────────────────
  {
    slug: 'kelly-snatch',
    name: 'Kelly Snatch',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💥',
  },
  {
    slug: '1-arm-snatch',
    name: '1 Arm Snatch',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💥',
  },
  {
    slug: 'triple-jump',
    name: 'Triple Jump',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'distance',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🦘',
  },
  {
    slug: 'javelin-throw',
    name: 'Javelin Throw',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'distance',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏹',
  },
  {
    slug: 'shot-put',
    name: 'Shot Put',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'distance',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'afl',
    name: 'AFL',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏉',
  },
  {
    slug: 'vertical-jump',
    name: 'Vertical Jump',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'distance',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⬆️',
  },
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🍑',
  },
  {
    slug: 'clean-and-jerk',
    name: 'Clean & Jerk',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },
  {
    slug: 'snatch',
    name: 'Snatch',
    domain: 'Power',
    domainNumber: 5,
    inputMode: 'strength',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏋️',
  },

  // ─── Domain 6: Aerobic Endurance ─────────────────────────────────────────────
  {
    slug: '200m-burpee-broad-jump',
    name: '200m Burpee Broad Jump',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💨',
  },
  {
    slug: '1k-run',
    name: '1k Run',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: 'Run 1 kilometre as fast as possible on a measured flat course or track. Start from standing. Timer starts on the judge\'s signal. Timer stops when both feet cross the finish line.',
    rules: 'Distance must be exactly 1 kilometre on a measured course. Running shoes or bare feet allowed. No cycling, skating, or assisted movement. Must run the full distance without cutting the course. Timer starts at the judge\'s signal and stops when you cross the finish line.',
    disadvantage: {
      small: ['Carry a 5kg weighted vest', 'Run backwards for 200m of the course', 'One shoe removed'],
      large: ['Carry a 10kg weighted vest', 'Run the entire distance backwards', 'Crawl the final 100m'],
    },
    videoPlaceholder: true,
    emoji: '🏃',
  },
  {
    slug: '1k-cycle',
    name: '1k Cycle',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🚴',
  },
  {
    slug: '1k-ski-erg',
    name: '1k Ski Erg',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⛷️',
  },
  {
    slug: '1k-row',
    name: '1k Row',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🚣',
  },
  {
    slug: 'iron-lungs',
    name: 'Iron Lungs',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'hold',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🫁',
  },
  {
    slug: '200m-carry',
    name: '200m Carry',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'weight+time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '📦',
  },
  {
    slug: '2k-run',
    name: '2k Run',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏃',
  },
  {
    slug: '200m-repeats',
    name: '200m Repeats',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏃',
  },
  {
    slug: 'bronco',
    name: 'Bronco',
    domain: 'Aerobic Endurance',
    domainNumber: 6,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🐴',
  },

  // ─── Domain 7: Speed & Agility ───────────────────────────────────────────────
  {
    slug: '100m-sprint',
    name: '100m Sprint',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sprint',
    hasDifficultyTiers: false,
    howToPerform: 'Sprint 100 metres from a standing start on a measured straight course. React to the judge\'s signal to start. Sprint at full speed to the finish line. Timer is recorded in seconds and centiseconds.',
    rules: 'Distance must be exactly 100 metres on a measured course. Standing start — no blocks required. Timer starts on the judge\'s signal, stops when you cross the finish line. Must stay in your lane. Time recorded as seconds + centiseconds (e.g. 12.34).',
    disadvantage: {
      small: ['Give opponent a 5m head start', 'Run in sand or on grass', 'Wear a 5kg weighted vest'],
      large: ['Give opponent a 10m head start', 'Run the entire distance backwards', 'Wear a 10kg weighted vest'],
    },
    videoPlaceholder: true,
    emoji: '💨',
  },
  {
    slug: 'tag',
    name: 'Tag',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏷️',
  },
  {
    slug: 't-race',
    name: 'T-Race',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚡',
  },
  {
    slug: '400m-race',
    name: '400m Race',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏃',
  },
  {
    slug: 'beach-flags',
    name: 'Beach Flags',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🚩',
  },
  {
    slug: '50m-sprint',
    name: '50m Sprint',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sprint',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚡',
  },
  {
    slug: '200m-sprint',
    name: '200m Sprint',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sprint',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💨',
  },
  {
    slug: 'touch-rugby',
    name: 'Touch Rugby',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏉',
  },
  {
    slug: 'football-dribble',
    name: 'Football Dribble',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚽',
  },
  {
    slug: 'repeat-high-jump',
    name: 'Repeat High Jump',
    domain: 'Speed & Agility',
    domainNumber: 7,
    inputMode: 'distance+time',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⬆️',
  },

  // ─── Domain 8: Body Awareness ─────────────────────────────────────────────────
  {
    slug: 'tae-kwon-do',
    name: 'Tae Kwon Do',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🥋',
  },
  {
    slug: 'breakdancing',
    name: 'Breakdancing',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'hold',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Toprock' },
      { level: 2, name: 'Footwork' },
      { level: 3, name: 'Freeze' },
      { level: 4, name: 'Power Move' },
      { level: 5, name: 'Combo (two elements)' },
      { level: 6, name: 'Full Routine (all four)' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '💃',
  },
  {
    slug: 'trampolining',
    name: 'Trampolining',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎪',
  },
  {
    slug: 'jump-rope',
    name: 'Jump Rope',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Two-Foot Basic' },
      { level: 2, name: 'Alternating Feet' },
      { level: 3, name: 'Single Leg' },
      { level: 4, name: 'Double Unders' },
      { level: 5, name: 'Triple Unders' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🪢',
  },
  {
    slug: 'wrestling',
    name: 'Wrestling',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤼',
  },
  {
    slug: 'gymnastics',
    name: 'Gymnastics',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'sport',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Log Roll' },
      { level: 2, name: 'Forward Roll' },
      { level: 3, name: 'Backward Roll' },
      { level: 4, name: 'Cartwheel' },
      { level: 5, name: 'Roundoff' },
      { level: 6, name: 'One-Hand Cartwheel' },
      { level: 7, name: 'Front Handspring' },
      { level: 8, name: 'Back Handspring' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤸',
  },
  {
    slug: 'balance-ball',
    name: 'Balance Ball',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'hold',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚖️',
  },
  {
    slug: 'skate',
    name: 'SKATE',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🛹',
  },
  {
    slug: 'fencing',
    name: 'Fencing',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤺',
  },
  {
    slug: 'juggling',
    name: 'Juggling',
    domain: 'Body Awareness',
    domainNumber: 8,
    inputMode: 'reps',
    hasDifficultyTiers: true,
    difficultyTiers: [
      { level: 1, name: 'Two Ball Two Hands' },
      { level: 2, name: 'Two Ball One Hand' },
      { level: 3, name: 'Three Ball' },
      { level: 4, name: 'Four Ball' },
    ],
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤹',
  },

  // ─── Domain 9: Co-ordination ─────────────────────────────────────────────────
  {
    slug: 'volleyball',
    name: 'Volleyball',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: 'Play a standard game of volleyball against your opponent. First to 21 points (win by 2) takes the match. Use standard volleyball rules. A judge or agreed witness must observe the match.',
    rules: 'Standard volleyball rules apply. First to 21 points wins (must win by 2). If no court is available, a modified court may be used with judge approval. Record win, draw (if agreed), or loss and the final score.',
    disadvantage: {
      small: ['Must use non-dominant hand only', 'Must sit to serve (all serves)', 'Only one touch per side allowed'],
      large: ['Must play on knees for the entire match', 'No overhand hits allowed (underarm only)', 'Opponent gets two touches per rally, you get one'],
    },
    videoPlaceholder: true,
    emoji: '🏐',
  },
  {
    slug: 'baseball',
    name: 'Baseball',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚾',
  },
  {
    slug: 'teqball',
    name: 'Teqball',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚽',
  },
  {
    slug: 'tennis',
    name: 'Tennis',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎾',
  },
  {
    slug: 'cricket',
    name: 'Cricket',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏏',
  },
  {
    slug: 'badminton',
    name: 'Badminton',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏸',
  },
  {
    slug: 'basketball',
    name: 'Basketball',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏀',
  },
  {
    slug: 'football',
    name: 'Football',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⚽',
  },
  {
    slug: 'hockey',
    name: 'Hockey',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏑',
  },
  {
    slug: 'squash',
    name: 'Squash',
    domain: 'Co-ordination',
    domainNumber: 9,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎾',
  },

  // ─── Domain 10: Aim & Precision ──────────────────────────────────────────────
  {
    slug: 'netball',
    name: 'Netball',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏀',
  },
  {
    slug: 'handball',
    name: 'Handball',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🤾',
  },
  {
    slug: 'cornhole',
    name: 'Cornhole',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎯',
  },
  {
    slug: 'dodgeball',
    name: 'Dodgeball',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎯',
  },
  {
    slug: 'carrom',
    name: 'Carrom',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎱',
  },
  {
    slug: 'archery',
    name: 'Archery',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🏹',
  },
  {
    slug: 'bowling',
    name: 'Bowling',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎳',
  },
  {
    slug: 'darts',
    name: 'Darts',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'sport',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🎯',
  },
  {
    slug: 'disc-golf',
    name: 'Disc Golf',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '🥏',
  },
  {
    slug: 'golf',
    name: 'Golf',
    domain: 'Aim & Precision',
    domainNumber: 10,
    inputMode: 'reps',
    hasDifficultyTiers: false,
    howToPerform: PLACEHOLDER_CONTENT,
    rules: PLACEHOLDER_CONTENT,
    disadvantage: PLACEHOLDER_DISADVANTAGE,
    videoPlaceholder: true,
    emoji: '⛳',
  },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getEventBySlug(slug: string): EventData | undefined {
  return EVENTS.find(e => e.slug === slug)
}

export function getEventByName(name: string): EventData | undefined {
  return EVENTS.find(e => e.name === name)
}

export function getEventsByDomain(): Record<string, EventData[]> {
  const map: Record<string, EventData[]> = {}
  for (const event of EVENTS) {
    if (!map[event.domain]) map[event.domain] = []
    map[event.domain].push(event)
  }
  return map
}

export function getDisadvantageOptions(eventName: string): DisadvantageOptions {
  return getEventByName(eventName)?.disadvantage ?? PLACEHOLDER_DISADVANTAGE
}

// ─── getBonusTargets ─────────────────────────────────────────────────────────
// Returns the 4 bonus tiers for a given event and season PR.
// seasonPR:
//   - strength → best weight_kg (numeric)
//   - time/sprint → best raw_score (negative seconds; more negative = faster)
//   - flexibility / tiered-hold events → best difficulty_tier string e.g. "D5"
//   - sport → null (always returns targets)
//   - all others → null (no targets)

function fmtSecs(totalSecs: number): string {
  const abs = Math.abs(totalSecs)
  const m = Math.floor(abs / 60)
  const s = Math.round(abs % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

export function getBonusTargets(
  event: EventData,
  seasonPR: number | string | null
): BonusTarget[] {
  const mode = event.inputMode

  // Sport events: always available, no PR needed
  if (mode === 'sport') {
    return ([1, 2, 3, 4] as const).map(tier => ({
      tier,
      label: `${tier} extra game${tier > 1 ? 's' : ''} vs a new opponent`,
      detail: `${tier} additional game${tier > 1 ? 's' : ''} vs different opponent${tier > 1 ? 's' : ''}`,
      points: 15 as const,
      inputMode: 'sport',
    }))
  }

  if (seasonPR === null) return []

  // Strength events: PR = best weight_kg
  if (mode === 'strength') {
    const prKg = typeof seasonPR === 'number' ? seasonPR : parseFloat(String(seasonPR))
    if (!prKg || isNaN(prKg)) return []
    const tiers: Array<{ tier: 1|2|3|4; pct: number; reps: number }> = [
      { tier: 1, pct: 0.9, reps: 3 },
      { tier: 2, pct: 0.8, reps: 5 },
      { tier: 3, pct: 0.7, reps: 8 },
      { tier: 4, pct: 0.6, reps: 12 },
    ]
    return tiers.map(({ tier, pct, reps }) => {
      const targetKg = Math.round(prKg * pct)
      return {
        tier,
        label: `${targetKg}kg × ${reps} reps`,
        detail: `${targetKg}kg × ${reps} reps`,
        points: 15 as const,
        inputMode: 'strength',
      }
    })
  }

  // Time/sprint events: PR = negative seconds (more negative = faster)
  if (mode === 'time' || mode === 'sprint') {
    const prSecs = typeof seasonPR === 'number' ? seasonPR : parseFloat(String(seasonPR))
    if (isNaN(prSecs)) return []
    const tiers: Array<{ tier: 1|2|3|4; efforts: number; pct: number }> = [
      { tier: 1, efforts: 1, pct: 0.90 },
      { tier: 2, efforts: 2, pct: 0.85 },
      { tier: 3, efforts: 3, pct: 0.80 },
      { tier: 4, efforts: 4, pct: 0.75 },
    ]
    return tiers.map(({ tier, efforts, pct }) => {
      const threshold = prSecs * pct
      const timeStr = fmtSecs(threshold)
      return {
        tier,
        label: `${efforts} effort${efforts > 1 ? 's' : ''} under ${timeStr}`,
        detail: `${efforts} effort${efforts > 1 ? 's' : ''}, each under ${timeStr}`,
        points: 15 as const,
        inputMode: mode,
      }
    })
  }

  // Flexibility & tiered hold events: PR = difficulty tier string e.g. "D5"
  const isFlexOrTieredHold =
    mode === 'flexibility' ||
    (event.hasDifficultyTiers && (event.domainNumber === 3 || event.domainNumber === 4))
  if (isFlexOrTieredHold) {
    const prTierStr = typeof seasonPR === 'string' ? seasonPR : null
    if (!prTierStr || !prTierStr.startsWith('D')) return []
    const prTierNum = parseInt(prTierStr.slice(1))
    if (isNaN(prTierNum)) return []

    const prTierName = event.difficultyTiers?.find(t => t.level === prTierNum)?.name ?? prTierStr
    const belowNum = prTierNum - 1
    const belowTierName = belowNum >= 1
      ? (event.difficultyTiers?.find(t => t.level === belowNum)?.name ?? `D${belowNum}`)
      : null

    const targets: BonusTarget[] = [{
      tier: 1,
      label: `Hold ${prTierStr} for 1 min`,
      detail: `Hold ${prTierName} for 1 minute`,
      points: 15,
      inputMode: 'hold',
    }]

    if (belowTierName) {
      targets.push({
        tier: 2,
        label: `Hold D${belowNum} for 2 min`,
        detail: `Hold ${belowTierName} for 2 minutes`,
        points: 15,
        inputMode: 'hold',
      })
      targets.push({
        tier: 3,
        label: `Hold D${belowNum} for 4 min`,
        detail: `Hold ${belowTierName} for 4 minutes`,
        points: 15,
        inputMode: 'hold',
      })
      targets.push({
        tier: 4,
        label: `Hold D${belowNum} for 6 min`,
        detail: `Hold ${belowTierName} for 6 minutes`,
        points: 15,
        inputMode: 'hold',
      })
    }

    return targets
  }

  return []
}

// Ordered domain list for consistent display
export const DOMAIN_ORDER = [
  'Maximal Strength',
  'Relative Strength',
  'Muscular Endurance',
  'Flexibility & Mobility',
  'Power',
  'Aerobic Endurance',
  'Speed & Agility',
  'Body Awareness',
  'Co-ordination',
  'Aim & Precision',
]
